config/routes.rb
# Rails.application.routes.draw do
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Defines the root path route ("/")
#   # root "posts#index"
# end


Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # métodos y configuraciones comunes aquí
  end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
        render "layouts/home"
    end
  
    def about
        render "layouts/about"
      
    end
  
    def contact
       render "layouts/contact"
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/about.html.erb
<h1>About us</h1>
<p>Information about our company or project.</p>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Copyright © 2024 Twitter. All rights reserved.</span>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>
 

app/views/layouts/contact.html.erb
<h1>Contact</h1>
<%= form_with scope: :contact, url: contact_path, local: true do |form| %>
  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :nombre %>
  </div>
  <div class="field">
    <%= form.label :Email%>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :Message %>
    <%= form.text_area :mensaje %>
  </div>
  <div class="actions">
    <%= form.submit 'Send' %>
  </div>
<% end %>

app/views/layouts/home.html.erb
<h1>Welcome to Antonio Ruiz-Tagle page</h1>
<p>This is the content of the home page</p>